CREATE TABLE `oa_chat` (
  `SESSION_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HOSTNAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SAMPLER_OPTS` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INPUT_TOKENS` text COLLATE utf8mb4_unicode_ci,
  `INFER_TOKENS` text COLLATE utf8mb4_unicode_ci,
  `STATS_PROMPT_DURATION_MS` int DEFAULT NULL,
  `STATS_INFER_DURATION_MS` int DEFAULT NULL,
  `STATS_INFER_TOKENS_PER_SECOND` float DEFAULT NULL,
  `STATS_PROMPT_TOKENS_PER_SECOND` float DEFAULT NULL,
  `LAST_UPDATE` timestamp NULL DEFAULT NULL,
  UNIQUE KEY `oa_chat_SESSION_ID_IDX` (`SESSION_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;